In [37]:
import pandas as pd
import numpy as np

In [39]:
data = 'https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv'

In [41]:
data = pd.read_csv(data) #Load the dataset

In [42]:
data.head()

,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,model_year,origin,fuel_type,drivetrain,num_doors,fuel_efficiency_mpg
0,170,3.0,159.0,3413.433759,17.7,2003,Europe,Gasoline,All-wheel drive,0.0,13.231729
1,130,5.0,97.0,3149.664934,17.8,2007,USA,Gasoline,Front-wheel drive,0.0,13.688217
2,170,NaN,78.0,3079.038997,15.1,2018,Europe,Gasoline,Front-wheel drive,0.0,14.246341
3,220,4.0,NaN,2542.392402,20.2,2009,USA,Diesel,All-wheel drive,2.0,16.912736
4,210,1.0,140.0,3460.870990,14.4,2009,Europe,Gasoline,All-wheel drive,2.0,12.488369

In [43]:
data.shape

(9704, 11)

In [44]:
data.shape[0] #return the total number of records in the dataset

9704

In [4]:
df = pd.read_csv(data) #Load the dataset and create data frame

In [5]:
len(df) # return the total number of records in the dataset

9704

In [6]:
pd.__version__

'3.0.3'

In [7]:
df.fuel_type

0       Gasoline
1       Gasoline
2       Gasoline
3         Diesel
4       Gasoline
          ...
9699      Diesel
9700    Gasoline
9701      Diesel
9702      Diesel
9703      Diesel
Name: fuel_type, Length: 9704, dtype: str

In [45]:
df.fuel_type.nunique()

2

In [46]:
df['fuel_type'].nunique()

2

In [47]:
num_fuel_types = df['fuel_type'].nunique() # Count unique fuel types

In [9]:
num_fuel_types

2

In [10]:
print(f"Number of unique fuel types : {num_fuel_types}")

Number of unique fuel types : 2

In [48]:
df.isnull()

,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,model_year,origin,fuel_type,drivetrain,num_doors,fuel_efficiency_mpg
0,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False
2,False,True,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...
9699,False,False,False,False,False,False,False,False,False,True,False
9700,False,True,False,False,False,False,False,False,False,False,False
9701,False,False,False,False,False,False,False,False,False,False,False
9702,False,False,False,False,False,False,False,False,False,False,False
9703,False,False,False,False,False,False,False,False,False,False,False

In [49]:
df.isnull().sum()

engine_displacement      0
num_cylinders          482
horsepower               0
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

In [50]:
missing_values = df.isnull().sum() # This shows exactly how many missing values are in each column.

In [51]:
print(missing_values)

engine_displacement      0
num_cylinders          482
horsepower               0
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

In [52]:
(data.isnull().sum() > 0).sum()

np.int64(4)

In [53]:
asia_cars = df[df['origin'] == 'Asia'] # Filter cars from Asia

In [54]:
asia_cars

,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,model_year,origin,fuel_type,drivetrain,num_doors,fuel_efficiency_mpg
8,250,1.0,174.0,2714.219310,10.3,2016,Asia,Diesel,Front-wheel drive,-1.0,16.823554
12,320,5.0,145.0,2783.868974,15.1,2010,Asia,Diesel,All-wheel drive,1.0,16.175820
14,200,6.0,160.0,3582.687368,14.9,2007,Asia,Diesel,All-wheel drive,0.0,11.871091
20,150,3.0,197.0,2231.808142,18.7,2011,Asia,Gasoline,Front-wheel drive,1.0,18.889083
21,160,4.0,133.0,2659.431451,NaN,2016,Asia,Gasoline,Front-wheel drive,-1.0,16.077730
...,...,...,...,...,...,...,...,...,...,...,...
9688,260,4.0,152.0,3948.404625,15.5,2018,Asia,Diesel,All-wheel drive,-1.0,11.054830
9692,180,3.0,188.0,3680.341381,18.0,2016,Asia,Gasoline,Front-wheel drive,1.0,11.711653
9693,280,2.0,148.0,2545.070139,15.6,2012,Asia,Diesel,All-wheel drive,0.0,17.202782
9698,180,1.0,131.0,3107.427820,13.2,2005,Asia,Gasoline,Front-wheel drive,-2.0,13.933716
9703,270,3.0,140.0,2908.043477,14.7,2005,Asia,Diesel,All-wheel drive,-1.0,14.884467

In [13]:
max_fuel_efficiency = df['fuel_efficiency_mpg'].max()

In [14]:
max_fuel_efficiency

np.float64(25.96722204888372)

In [15]:
asia_cars = df[df['origin'] == 'Asia'] # Filter cars from Asia

In [16]:
max_fuel_efficiency = asia_cars['fuel_efficiency_mpg'].max()

In [17]:
print(f"Maximum Fuel Efficiency: {max_fuel_efficiency}")

Maximum Fuel Efficiency: 23.759122836520497

In [18]:
df

,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,model_year,origin,fuel_type,drivetrain,num_doors,fuel_efficiency_mpg
0,170,3.0,159.0,3413.433759,17.7,2003,Europe,Gasoline,All-wheel drive,0.0,13.231729
1,130,5.0,97.0,3149.664934,17.8,2007,USA,Gasoline,Front-wheel drive,0.0,13.688217
2,170,NaN,78.0,3079.038997,15.1,2018,Europe,Gasoline,Front-wheel drive,0.0,14.246341
3,220,4.0,NaN,2542.392402,20.2,2009,USA,Diesel,All-wheel drive,2.0,16.912736
4,210,1.0,140.0,3460.870990,14.4,2009,Europe,Gasoline,All-wheel drive,2.0,12.488369
...,...,...,...,...,...,...,...,...,...,...,...
9699,140,5.0,164.0,2981.107371,17.3,2013,Europe,Diesel,Front-wheel drive,NaN,15.101802
9700,180,NaN,154.0,2439.525729,15.0,2004,USA,Gasoline,All-wheel drive,0.0,17.962326
9701,220,2.0,138.0,2583.471318,15.1,2008,USA,Diesel,All-wheel drive,-1.0,17.186587
9702,230,4.0,177.0,2905.527390,19.4,2011,USA,Diesel,Front-wheel drive,1.0,15.331551
9703,270,3.0,140.0,2908.043477,14.7,2005,Asia,Diesel,All-wheel drive,-1.0,14.884467

In [19]:
median_hp = df['horsepower'].median() #selects the horsepower column and computes median value

In [20]:
print(median_hp)

149.0

In [55]:
df['horsepower'].mode()

0    152.0
Name: horsepower, dtype: float64

In [56]:
most_frequent_hp = df['horsepower'].mode()

In [57]:
most_frequent_hp

0    152.0
Name: horsepower, dtype: float64

In [21]:
most_frequent_hp = df['horsepower'].mode()[0] #returns a series of the most frequent values in the horsepower column and selects the one that occurs the most

In [22]:
print("Most frequent Horsepower:", most_frequent_hp)

Most frequent Horsepower: 152.0

In [58]:
df.horsepower.isnull()

0       False
1       False
2       False
3       False
4       False
        ...
9699    False
9700    False
9701    False
9702    False
9703    False
Name: horsepower, Length: 9704, dtype: bool

In [23]:
df['horsepower'] = df['horsepower'].fillna(most_frequent_hp) # Fill missing values with the most frequent value

In [24]:
print(df['horsepower'].isnull().sum()) # Verify there are no missing values left

0

In [25]:
df

,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,model_year,origin,fuel_type,drivetrain,num_doors,fuel_efficiency_mpg
0,170,3.0,159.0,3413.433759,17.7,2003,Europe,Gasoline,All-wheel drive,0.0,13.231729
1,130,5.0,97.0,3149.664934,17.8,2007,USA,Gasoline,Front-wheel drive,0.0,13.688217
2,170,NaN,78.0,3079.038997,15.1,2018,Europe,Gasoline,Front-wheel drive,0.0,14.246341
3,220,4.0,152.0,2542.392402,20.2,2009,USA,Diesel,All-wheel drive,2.0,16.912736
4,210,1.0,140.0,3460.870990,14.4,2009,Europe,Gasoline,All-wheel drive,2.0,12.488369
...,...,...,...,...,...,...,...,...,...,...,...
9699,140,5.0,164.0,2981.107371,17.3,2013,Europe,Diesel,Front-wheel drive,NaN,15.101802
9700,180,NaN,154.0,2439.525729,15.0,2004,USA,Gasoline,All-wheel drive,0.0,17.962326
9701,220,2.0,138.0,2583.471318,15.1,2008,USA,Diesel,All-wheel drive,-1.0,17.186587
9702,230,4.0,177.0,2905.527390,19.4,2011,USA,Diesel,Front-wheel drive,1.0,15.331551
9703,270,3.0,140.0,2908.043477,14.7,2005,Asia,Diesel,All-wheel drive,-1.0,14.884467

In [26]:
median_hp = df['horsepower'].median() #selects the horsepower column and computes median value

In [27]:
print(median_hp)

152.0

In [28]:
asian_cars = df[df['origin'] == 'Asia'] # Filter rows where Region is 'Asia'

In [60]:
X = asian_cars[['vehicle_weight', 'model_year']] # Select only 'vehicle_weight' and 'model_year' columns

In [91]:
X.head(7)

,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,model_year,origin,fuel_type,drivetrain,num_doors,fuel_efficiency_mpg
8,250,1.0,174.0,2714.219310,10.3,2016,Asia,Diesel,Front-wheel drive,-1.0,16.823554
12,320,5.0,145.0,2783.868974,15.1,2010,Asia,Diesel,All-wheel drive,1.0,16.175820
14,200,6.0,160.0,3582.687368,14.9,2007,Asia,Diesel,All-wheel drive,0.0,11.871091
20,150,3.0,197.0,2231.808142,18.7,2011,Asia,Gasoline,Front-wheel drive,1.0,18.889083
21,160,4.0,133.0,2659.431451,NaN,2016,Asia,Gasoline,Front-wheel drive,-1.0,16.077730
34,150,2.0,149.0,2844.227534,17.3,2014,Asia,Diesel,Front-wheel drive,0.0,15.353788
38,190,5.0,158.0,3761.994038,NaN,2019,Asia,Gasoline,Front-wheel drive,1.0,11.645724

In [92]:
X = X.head(7)

In [94]:
X = X[['vehicle_weight', 'model_year']] # Select only 'vehicle_weight' and 'model_year' columns

In [95]:
X

    vehicle_weight  model_year
8      2714.219310        2016
12     2783.868974        2010
14     3582.687368        2007
20     2231.808142        2011
21     2659.431451        2016
34     2844.227534        2014
38     3761.994038        2019

In [96]:
X.values #get underlying numpy array

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

In [97]:
X = X.values #get underlying numpy array

In [98]:
X

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

In [ ]:
X = X.to_numpy() # Convert to NumPy array

In [ ]:
X

In [99]:
XT = X.T
XT

array([[2714.21930965, 2783.86897424, 3582.68736772, 2231.8081416 ,
        2659.43145076, 2844.22753389, 3761.99403819],
       [2016.        , 2010.        , 2007.        , 2011.        ,
        2016.        , 2014.        , 2019.        ]])

In [100]:
X.shape

(7, 2)

In [101]:
XT.shape

(2, 7)

In [102]:
XTX = XT.dot(X) # Compute matrix-matrix multiplication between the transpose of X and X.

In [103]:
XTX = np.dot(XT , X) # Compute matrix-matrix multiplication between the transpose of X and X.

In [104]:
XTX

array([[62248334.33150762, 41431216.5073268 ],
       [41431216.5073268 , 28373339.        ]])

In [105]:
XTX_inv = np.linalg.inv(XTX) # compute Invert XTX

In [106]:
XTX_inv

array([[ 5.71497081e-07, -8.34509443e-07],
       [-8.34509443e-07,  1.25380877e-06]])

In [107]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

In [108]:
y

array([1100, 1300,  800,  900, 1000, 1100, 1200])

In [111]:
XTX_inv_XT = XTX_inv.dot(XT)

In [112]:
XTX_inv_XT

array([[-1.31202622e-04, -8.63909858e-05,  3.72634923e-04,
        -4.02726650e-04, -1.62513724e-04, -5.52342829e-05,
         4.65094049e-04],
       [ 2.62636846e-04,  1.96990690e-04, -4.73392228e-04,
         6.58944477e-04,  3.08357831e-04,  1.51636137e-04,
        -6.07979633e-04]])

In [113]:
XTX_inv_XT_y = XTX_inv_XT.dot(y)

In [114]:
XTX_inv_XT_y

array([0.01386421, 0.5049067 ])

In [115]:
w = XTX_inv_XT_y

In [116]:
w

array([0.01386421, 0.5049067 ])

In [117]:
w = (XTX_inv @ X.T) @ y